# Site settings
title: Liquorice Labs - We're up to allsorts!
email:
description: > # this means to ignore newlines until "baseurl:"
  Liquorice labs - sweet solutions to deliciously complex problems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://liquoricelabs.com" # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright: Liquorice Labs

# API settings
google_api_key:

# Build settings
markdown: kramdown
